<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NewtonsoftJsonPath Condition="'$(NewtonsoftJsonPath)' == ''">../../Library/PackageCache/com.unity.nuget.newtonsoft-json@3.0.2/Runtime/Newtonsoft.Json.dll</NewtonsoftJsonPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Assets/Scripts/ChatGPT/*.cs" />
    <Compile Include="Program.cs" />
    <Reference Include="Newtonsoft.Json"><HintPath>$(NewtonsoftJsonPath)</HintPath></Reference>
  </ItemGroup>
</Project>
